Working sign in & register
null-uw/Beacon pull request #4
Opened 2019-05-17 06:42 UTC by joesyoon

2019-05-21 22:41 UTC, bbasinsk requested changes

2019-05-21 22:41 UTC, bbasinsk commented on android/app/local.properties
> +## This file must *NOT* be checked into Version Control Systems,
Could you remove this file from this PR?

2019-05-23 23:04 UTC, bbasinsk commented
Overall, I'm not too keen on the UI, but that can be changed later. We also need to make sure that we are updating the user's name when we register them. Right now it's just an input that's not doing anything

2019-05-23 23:05 UTC, matthewkli97 commented
Since this isn't blocking any progress atm, can we get this to be refactored using the pattern found in this medium post?

https://medium.com/flutterpub/flutter-how-to-do-user-login-with-firebase-a6af760b14d5

2019-05-30 23:05 UTC, closed without merging